name = "fomoholdersapi"
main = "src/worker.js"
compatibility_date = "2026-03-24"

[[kv_namespaces]]
binding = "FOMO_KV"
id = "REPLACE_WITH_PROD_KV_NAMESPACE_ID"
preview_id = "REPLACE_WITH_PREVIEW_KV_NAMESPACE_ID"
